version: '3.8'

services:
    app:
        container_name: app-capture-live
        build:
            context: .
            target: development
            args:
                # UID and GID must be set as environment variables on the host machine
                USER_ID: $UID
                GROUP_ID: $GID
        ports:
            - '80:8080'
        volumes:
            - .:/var/www/html

    redis:
        image: redis:6
        container_name: redis-capture-live
        ports:
            - '${REDIS_PORT}:${REDIS_PORT}'
        command: "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
