services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"  # Enable Traefik dashboard (optional)
      - "--providers.docker=true"  # Use Docker provider
      - "--entrypoints.web.address=:80"  # Define entrypoint for HTTP
      - "--entrypoints.websecure.address=:443"  # Define entrypoint for HTTPS
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"  # Enable TLS-ALPN challenge
      # Alternatively, use DNS-01 challenge with Cloudflare
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=${CF_API_EMAIL}"  # Your email for Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"  # Where to store certs
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "8080:8080"  # Traefik dashboard (optional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Enable Docker provider
      - "./letsencrypt:/letsencrypt"  # Volume for Let's Encrypt certs
    environment:
      - "CF_API_EMAIL=${CF_API_EMAIL}"  # Your Cloudflare account email
      - "CF_API_KEY=${CF_API_KEY}"  # Cloudflare global API key or API token
    networks:
      - traefik

  app:
    container_name: app-capture-live
    image: bartek2k/capture-live-api:latest
    ports:
      - '80:8080'
      - '443:8443'
    env_file:
      - .env
    networks:
      - capture-live-network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-capture-live.rule=Host(`api.bartlomiejcisek.online`)"
      - "traefik.http.services.app-capture-live.loadbalancer.server.port=80"

  task:
    image: bartek2k/capture-live-api:latest
    container_name: task-capture-live
    env_file:
      - .env
    command: [ "php", "/var/www/html/artisan", "schedule:work" ]
    stop_signal: SIGTERM # Set this for graceful shutdown if you're using fpm-apache or fpm-nginx
    healthcheck:
      # This is our native healthcheck script for the scheduler
      test: [ "CMD", "healthcheck-schedule" ]
      start_period: 10s
    networks:
      - capture-live-network

  redis:
    image: redis:6
    container_name: redis-capture-live
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data
    restart: always
    networks:
      - capture-live-network

  postgres:
    image: postgres:17-alpine
    container_name: db-capture-live
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - capture-live-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  capture-live-network:
    driver: bridge
  traefik:
    external: true
