services:
  traefik:
    image: traefik:v3.1.5
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - certs:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    restart: unless-stopped
    networks:
      - traefik

  app:
    container_name: app-capture-live
    image: bartek2k/capture-live-api:latest
    env_file:
      - .env
    networks:
      - capture-live-network
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-capture-live.rule=Host(`api.bartlomiejcisek.online`)
      - traefik.http.routers.app-capture-live.entrypoints=web
      - traefik.http.routers.app-capture-live-https.tls=true
      - traefik.http.routers.app-capture-live-https.tls.certresolver=cloudflare
      - traefik.http.routers.app-capture-live-https.entrypoints=websecure
      - traefik.http.routers.app-capture-live-https.rule=Host(`api.bartlomiejcisek.online`)

  task:
    image: bartek2k/capture-live-api:latest
    container_name: task-capture-live
    env_file:
      - .env
    command: [ "php", "/var/www/html/artisan", "schedule:work" ]
    stop_signal: SIGTERM # Set this for graceful shutdown if you're using fpm-apache or fpm-nginx
    healthcheck:
      # This is our native healthcheck script for the scheduler
      test: [ "CMD", "healthcheck-schedule" ]
      start_period: 10s
    restart: unless-stopped
    networks:
      - capture-live-network

  redis:
    image: redis:6
    container_name: redis-capture-live
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data
    restart: unless-stopped
    networks:
      - capture-live-network

  postgres:
    image: postgres:17-alpine
    container_name: db-capture-live
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - capture-live-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  certs:
    driver: local

networks:
  capture-live-network:
    driver: bridge
  traefik:
    external: true
