services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capture-live-app
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:6.0
    container_name: capture-live-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
